---
title: "EDLD 654 Lab 5: Claire, Thuy, Jim"
output:
  html_document: 
    toc: true
    toc_float: true
    theme: "journal"
    css: "website-custom.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
library(tidymodels)
library(tune)
library(glmnet)
library(baguette)
library(parsnip)
library(doParallel)
library(vip)
library(pdp)
library(patchwork)
library(ranger)
```

# Data 

```{r, include=TRUE}
set.seed(3000)
data <- read_csv(here::here("data", "train.csv")) %>% 
  select(-classification)

data <- dplyr::sample_frac(data, size = 0.01)

sheets <- readxl::excel_sheets(here::here("data",
"fallmembershipreport_20192020.xlsx"))

ode_schools <- readxl::read_xlsx(here::here("data",
"fallmembershipreport_20192020.xlsx"), sheet = sheets[4])

ethnicities <- ode_schools %>%
select(attnd_schl_inst_id = `Attending School ID`,
sch_name = `School Name`,
contains("%")) %>%
janitor::clean_names()
names(ethnicities) <- gsub("x2019_20_percent", "p", names(ethnicities))

data <- left_join(data, ethnicities)
head(data)
```

# Split and Resample 

```{r, include=TRUE}
set.seed(3000)
data_split <- initial_split(data, strata = "score")

set.seed(3000)
train <- training(data_split)
test <- testing(data_split)

set.seed(3000)
data_cv <- vfold_cv(train, strata = "score")

```

# Preprocess 

```{r, include=FALSE}
rec <- recipe(
    formula = score ~ gndr + ethnic_cd + econ_dsvntg + enrl_grd, 
    data = train 
  ) %>%
  step_naomit(everything(), skip = TRUE) %>% 
  step_string2factor(gndr, ethnic_cd, econ_dsvntg) %>%  
  step_dummy(gndr, ethnic_cd, econ_dsvntg) %>% 
  step_normalize(enrl_grd)

prep(rec)
```

# Decision Tree 

## Model and Workflow

```{r, include=TRUE}

mod_random1 <- decision_tree() %>% 
  set_mode("regression") %>% 
  set_engine("rpart") %>% 
  set_args(cost_complexity = 0.01, min_n = 5)



random1_wflow <- workflow() %>%
add_recipe(rec) %>%
add_model(mod_random1)

fit1 <- fit_resamples(random1_wflow, data_cv)

collect_metrics(fit1)

```

## Tune

```{r, include=TRUE}
tune_model <- decision_tree() %>% 
  set_mode("regression") %>% 
  set_engine("rpart") %>% 
  set_args(cost_complexity = tune(), min_n = tune())

grd <- grid_regular(cost_complexity(), min_n(), levels = c(10, 5))
grd


metrics_eval <- metric_set(rmse,
                           rsq,
                           huber_loss)

tictoc::tic()
tune_tree <- tune_grid(tune_model, 
                       rec, 
                       data_cv, 
                       grid = grd, 
                       metrics = metrics_eval)
tictoc::toc()

```

## Best Estimates 

```{r, include=TRUE}
show_best(tune_tree, "rmse")

show_best(tune_tree, "rsq")

show_best(tune_tree, "huber_loss")
```






# Bagged Tree

## Model and Workflow

```{r, include=TRUE}
mod_bagged_tree <- bag_tree() %>% 
  set_mode("regression") %>% 
  set_args(cost_complexity = 0, min_n = 2) %>% 
  set_engine("rpart", times = 10) 


bagged_wflow <- workflow() %>%
add_recipe(rec) %>%
add_model(mod_bagged_tree)

bagged_fit <- fit_resamples(bagged_wflow, data_cv)

collect_metrics(bagged_fit)
```

## Tune

```{r, include=TRUE}

bag_model_tune <- bag_tree() %>% 
  set_mode("regression") %>% 
  set_args(cost_complexity = tune(), min_n = tune()) %>% 
  set_engine("rpart", times = 10)


tree_grid <- grid_max_entropy(cost_complexity(), min_n(), size = 10)



plan(multisession)
tictoc::tic()
bag_tune <- tune_grid(bag_model_tune,
                      rec,
                      data_cv,
                      grid = tree_grid,
                      metrics = metrics_eval,
                      extract = function(x) extract_model(x))
tictoc::toc()
```

## Best Estimates 

Answer to question prior to running code:

```{r, include=TRUE}
show_best(bag_tune, "rmse")

show_best(bag_tune, "rsq")

show_best(bag_tune, "huber_loss")
```

## Bag Roots Function

```{r, include=TRUE}
bag_roots <- function(x){
  x %>% 
  select(.extracts) %>% 
  unnest(cols = c(.extracts)) %>% 
  mutate(models = map(.extracts,
                  ~.x$model_df)) %>% 
  select(-.extracts) %>% 
  unnest(cols = c(models)) %>% 
  mutate(root = map_chr(model,
                     ~as.character(.x$fit$frame[1, 1]))) %>%
  select(root)  
}
```

## Plot

```{r, include=TRUE}


```






# Random Forest 

## Model 

```{r, include=TRUE}



floor(sqrt(39))

(cores <- parallel::detectCores())

rf_def_mod <-
  rand_forest() %>% 
  set_engine("ranger",
             num.threads = cores, 
             importance = "permutation",  
             verbose = TRUE) %>% 
  set_mode("regression") %>% 
  set_args(mtry = NULL,
           trees = 1000,
           min_n = NULL)
           

translate(rf_def_mod)

```

## Workflow

```{r, include=TRUE}
rf_wflow <- workflow() %>%
  add_model(rf_def_mod) %>% 
  add_recipe(rec)
```

## Fit

```{r, include=TRUE}
tictoc::tic()
set.seed(3000)
rf_def_res <- fit_resamples(
  rf_wflow,
  data_cv,
  metrics = metrics_eval,
  control = control_resamples(verbose = TRUE,
                              save_pred = TRUE,
                              extract = function(x) x)
                              )
tictoc::tic()

head(rf_def_res)
```

## ## Best Estimates 

```{r, include=TRUE}
show_best(rf_def_res, "rmse")

show_best(rf_des_res, "rsq") #not sure why this line isn't running

show_best(rf_def_res, "huber_loss")
```

## Function Code Provided 

```{r, include=TRUE}
rf_tree_roots <- function(x){
  map_chr(1:1000, 
           ~ranger::treeInfo(x, tree = .)[1, "splitvarName"])
}

rf_roots <- function(x){
  x %>% 
  select(.extracts) %>% 
  unnest(cols = c(.extracts)) %>% 
  mutate(fit = map(.extracts,
                   ~.x$fit$fit$fit),
         oob_rmse = map_dbl(fit,
                         ~sqrt(.x$prediction.error)),
         roots = map(fit, 
                        ~rf_tree_roots(.))
         ) %>% 
  select(roots) %>% 
  unnest(cols = c(roots))
}

rf_roots(rf_def_res)

```

## Plot

```{r, include=TRUE}
head(rf_def_res)

rf_def_res %>% 
  pluck(".workflow", 1)

rf_def_res %>% 
  pluck(".workflow", 1) %>% 
  pull_workflow_fit() %>% 
  vip()

rlang::last_error()
```